Notifcations/Controllers/NotifcationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Notifcations.Hubs;
using Notifcations.Hubs.ServicesHub;
using Notifcations.Models.Entities;
using Notifcations.Utlties.Services;
using Notifcations.ViewModels;

namespace Notifcations.Controllers {
    [Authorize(Roles ="Admin")]
    public class NotifcationController : Controller {
        private readonly IMapper _mapper;
        private readonly IServices _services;
        private readonly UserManager<Appuser> _userManager;
        private readonly IHttpContextAccessor _httpContext;
        private readonly IHubContext<NotificationUserHub> _notificationUserHubContext;
        private readonly IUserConnectionManager _userConnectionManager;
        public NotifcationController(IMapper mapper, UserManager<Appuser> userManager, IServices services, IHttpContextAccessor httpContext, IHubContext<NotificationUserHub> notificationUserHubContext, IUserConnectionManager userConnectionManager)
        {
            _mapper = mapper;
            _userManager = userManager;
            _services = services;
            _httpContext = httpContext;
            _notificationUserHubContext = notificationUserHubContext;
            _userConnectionManager = userConnectionManager;
        }
        [HttpGet]
        public async Task<IActionResult> SendMessage()
        {
            IEnumerable<Appuser> appusers = await _userManager.GetUsersInRoleAsync("User");
            ViewBag.Users = new SelectList(appusers.Select(b => b.Email));
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendMessage(MessageViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.UserId);
                if (user != null)
                {
                    model.UserId = user.Id;
                    var message = _mapper.Map<Message>(model);
                    if (_services.CreateMessage(message).Result > 0)
                    {
                     
                    }
                }
                ModelState.AddModelError(string.Empty, "مش لاقي البنادم ده");
            }

            return View(model);
        }
    }
}

Notifcations/Views/Notifcation/SendMessage.cshtml
@model MessageViewModel;
@{
    ViewData["Title"] = "Send To User";
}
<form method="post" asp-area="" asp-controller="Notifcation" asp-action="SendMessage" asp-antiforgery="true">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group  mt-4">
        <label  class="form-label">Send To</label>
        <select asp-for="UserId" asp-items="ViewBag.Users" class="form-control">
          <option selected disabled>--اختر بني ادم--</option>
      </select>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>
    <div class="form-group  mt-4">
        <label asp-for="Text" class="form-label">Message</label>
        <textarea asp-for="Text" cols="40" rows="10" class="form-control"></textarea>
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="form-group  mt-4">
        <input type="submit" value="Send" class="btn btn-primary" id="send" />
    </div>
</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Notifcations/Views/Notifcation/Sucess.cshtml
@{
    ViewData["Title"] = "Done";
}
<div>
    <img src="~/Images/Vertict.svg" alt="img" style="width:50%;margin-left:30%" /><br/>
    <a asp-area="" asp-action="SendMessage" asp-controller="Notifcation" class="btn btn-danager">Back</a>
</div>